### ISSUE TITLE
ignore error undefined

### ISSUE THREAD

**Issue by seb-wahl** [esm-tools/esm_master#39]
I use the following versions:
```
blogin3:~/esm/esm_tools/stuff/test_setups $ esm_versions check
+---------------------+-----------+---------------------------------------------------+-------------------------+----------------------------+
| package_name        | version   | file                                              | branch                  | tags                       |
|---------------------+-----------+---------------------------------------------------+-------------------------+----------------------------|
| esm_calendar        | 5.0.0     | /home/shkifmsw/.local/lib/python3.7/site-packages |                         |                            |
| esm_database        | 5.0.0     | /home/shkifmsw/.local/lib/python3.7/site-packages |                         |                            |
| esm_environment     | 5.0.0     | /home/shkifmsw/.local/lib/python3.7/site-packages |                         |                            |
| esm_master          | 5.0.4     | /home/shkifmsw/.local/lib/python3.7/site-packages |                         |                            |
| esm_motd            | 5.0.2     | /home/shkifmsw/.local/lib/python3.7/site-packages |                         |                            |
| esm_parser          | 5.0.5     | /home/shkifmsw/esm/esm_parser                     | develop                 | v5.0.7-14-g6545da3         |
| esm_plugin_manager  | 5.0.1     | /home/shkifmsw/.local/lib/python3.7/site-packages |                         |                            |
| esm_profile         | 5.0.0     | /home/shkifmsw/.local/lib/python3.7/site-packages |                         |                            |
| esm_rcfile          | 5.0.0     | /home/shkifmsw/esm/esm_rcfile                     | develop                 | v5.0.0-3-gc1d2efe          |
| esm_runscripts      | 5.0.3     | /home/shkifmsw/.local/lib/python3.7/site-packages | develop                 | v5.0.17-65-gbcdff80        |
| esm_tools           | 5.0.12    | /home/shkifmsw/esm/esm_tools                      | feature/fix_test_script | v5.0.12-124-g4ecd097-dirty |
| esm_version_checker | 5.1.2     | /home/shkifmsw/.local/lib/python3.7/site-packages |                         |                            |
+---------------------+-----------+---------------------------------------------------+-------------------------+----------------------------+
blogin3:~/esm/esm_tools/stuff/test_setups $
```
on blogin. If I try to run `esm_master get-foci-default` it fails with
```bash
blogin3:~/esm/esm_tools/stuff/test_setups $ esm_master get-foci-default
************************************************************************************
Message found for package esm_tools version 5.0.12:

"ESM Tools version 5.0.5 allows for the generation of hosing files in AWI-ESM-2.1 and AWI-ESM-2.2
To use that, you still need to install a plugin. Please run:

$ pip install --user gfw_creator"

Upgrade this package by typing:              esm_versions upgrade esm_tools
Upgrade all packages by typing:              esm_versions upgrade
************************************************************************************
    Executing commands in this order:
         mkdir -p foci-default
         cd foci-default
         git clone -b oasis3mct2.8-foci https://git.geomar.de/foci/src/oasis3mct.git oasis
         git clone -b esm-tools https://git.geomar.de/foci/src/echam.git echam-6.3.05p2-foci
         git clone -b esm-tools https://git.geomar.de/foci/src/xios.git xios
         git clone -b esm-tools https://git.geomar.de/foci/src/nemo.git nemo-ORCA05_LIM2_KCM_AOW
         git clone -b master https://git.geomar.de/foci/src/nemo_config/ORCA05_LIM2_KCM_AOW.git nemo-ORCA05_LIM2_KCM_AOW/CONFIG/ORCA05_LIM2_KCM_AOW
         sed -i '/ECHAM6_COUPLED/s/OFF/ON/g' echam-6.3.05p2-foci/CMakeLists.txt
         cd ..
Traceback (most recent call last):
  File "/home/shkifmsw/.local/bin/esm_master", line 10, in <module>
    sys.exit(main())
  File "/home/shkifmsw/.local/lib/python3.7/site-packages/esm_master/cli.py", line 76, in main
    main_flow(parsed_args, target)
  File "/home/shkifmsw/.local/lib/python3.7/site-packages/esm_master/esm_master.py", line 52, in main_flow
    user_task.execute() #env)
  File "/home/shkifmsw/.local/lib/python3.7/site-packages/esm_master/task.py", line 474, in execute
    check= not ignore_errors,
NameError: name 'ignore_errors' is not defined
blogin3:~/esm/esm_tools/stuff/test_setups $
```
Must have been introduced during one of the latest merge, as esm_master 5.0.1 was still working.

**Comment by mandresm** [comment]
Sorry @seb-wahl , my bad... It should work now after doing `esm_versions upgrade esm_master`.
